---
title: "MTH 2520 - R Programming"
author: "Type Your Name Here"
subtitle: 'Homework 4: Vectors, Part II'
output:
  pdf_document: default
  word_document:
    reference_docx: ../../WordStyleRef-01.docx
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, comment="")
library(rmarkdown, tinytex)

```

***


Pr. 1 Basic stats

```{r}
data <- c(1.2,-3.5,4.3,8.6,-5.1)
summary(data)
cat("The sample mean is",mean(data),"\n")
cat("The sample standard deviation is",sd(data),"\n")
cat("The interquartile range is",IQR(data),"\n")
```
<!-- The following commands are computing R inline. You won't see these executed until you knit the document-->

The mean of the data set is `r mean(data)`.

The median of the data set is `r median(data)`.

The sample standard deviation is `r sd(data)`.

The interquartile range is `r IQR(data)`


***
Pr. 2

```{r}
data2 <- c(4.1, 4.3, 4.7, 3.4, 3.9, 5.6, 4.6, NA, 6.6, 5.1, 4.3, 49, NA, 4.4, 6.1)

# I'm going to replicate the formatting from your answer to problem 1. It looks so clean! 

cat("The sample mean is", mean(data2, na.rm = TRUE), "\n")
cat("The standard deviation of this sample is", sd(data2, na.rm = TRUE), "\n")
cat("The median of this sample is", median(data2, na.rm = TRUE), "\n")
cat("The interquartile range of this sample is", IQR(data2, na.rm = TRUE), "\n")
```


***
Pr. 3

```{r}
xdata <- read.csv("hw4_x.csv",sep="")
cat("The type of data is", typeof(xdata), "\n")

summary(xdata)
cat("The standard deviation of ydata is", sd(xdata$x, na.rm = TRUE), "\n")
cat("The interquartile rnage of ydata is", IQR(xdata$x, na.rm = TRUE), "\n")

```


```{r, fig.width = 4, fig.height = 4}
hist(xdata$x,main="Histogram of the Data Set x",xlab="x",col="magenta")
```

***
Pr. 4

```{r}
ydata <- read.csv("hw4_y.csv",sep="")
cat("The type of data is", typeof(ydata), "\n")

summary(ydata)
cat("The standard deviation of ydata is", sd(ydata$y), "\n")
cat("The interquartile rnage of ydata is", IQR(ydata$y), "\n")

```


```{r, fig.width = 4, fig.height = 4}
hist(ydata$y,main="Histogram of the Data Set y",xlab="y",col="yellow")
```













